### ISSUE TITLE
Porting lace to windows

### ISSUE THREAD

**Issue by blizzard4591** [trolando/lace#2]
Dear lace-team,

I am currently porting lace to windows.

In a first step, I replaced the lace.sh and prepare.sh scripts by equivalent CMake implementations that generate both the lace-x.h and lace-x.c files.

During this, I noticed a bug in lace.sh, line 170. There is a semicolon after "TASK_COMMON_FIELDS(_Task)", but the macro is not designed to be ended with a semicolon.

A more intriguing bug, or feature, is the use of arrays with size 0.

In the struct _Task we have:

```
char p1[PAD(LACE_COMMON_FIELD_SIZE, P_SZ)];
```

This evaluates to zero, but the ISO C standard explicitly states that constant array sizes must be strictly greater than zero (ISO 9899:2011 6.7.6.2:). I assume GCC allows this, but MSVC unfortunately does not.

I think this is also used in this check:

```
typedef char assertion_failed_task_descriptor_out_of_bounds_##NAME[(sizeof(TD_##NAME)<=sizeof(Task)) ? 0 : -1];
```

Should I prepare mergeable commits?
I would prepare one set containing fixes and another set containing the cross-platform adaptions.

**Comment by blizzard4591** [comment]
Another problem is this definition:
```
typedef struct _TD_##NAME {
  TASK_COMMON_FIELDS(_TD_##NAME)
  union {
    struct { $TASK_FIELDS } args;
    $RES_FIELD
  } d;
} TD_##NAME;
```
In the first run, TASK_FIELDS is empty, therefore the struct args is empty - this is illegal (a struct may not be empty).

**Comment by blizzard4591** [comment]
Additional hint for calls to mmap() (from the documentation of mmap()):
MAP_ANONYMOUS
              The mapping is not backed by any file; its contents are
              initialized to zero.  The fd and offset arguments are ignored;
              however, some implementations require fd to be -1 if
              MAP_ANONYMOUS (or MAP_ANON) is specified, and portable
              applications should ensure this.  The use of MAP_ANONYMOUS in
              conjunction with MAP_SHARED is supported on Linux only since
              kernel 2.4.

In almost every instance, fd is set to 0 instead of -1.
Only a small problem, but worth fixing.

**Comment by dumblob** [comment]
Hm, does lace run on Windows with the above-mentioned issues and concerns mitigated?
